// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using obras_mvc_ef.Data;

#nullable disable

namespace obras_mvc_ef.Migrations
{
    [DbContext(typeof(GaleriaDbContext))]
    partial class GaleriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExposicionObras", b =>
                {
                    b.Property<int>("ExposicionesObrasId")
                        .HasColumnType("int");

                    b.Property<Guid>("ObrasExpuestasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExposicionesObrasId", "ObrasExpuestasId");

                    b.HasIndex("ObrasExpuestasId");

                    b.ToTable("ExposicionObras");
                });

            modelBuilder.Entity("obras_mvc_ef.Models.Artista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("obras_mvc_ef.Models.Exposicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exposiciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaFin = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Expo especial"
                        });
                });

            modelBuilder.Entity("obras_mvc_ef.Models.Obras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("ExposicionObras", b =>
                {
                    b.HasOne("obras_mvc_ef.Models.Exposicion", null)
                        .WithMany()
                        .HasForeignKey("ExposicionesObrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("obras_mvc_ef.Models.Obras", null)
                        .WithMany()
                        .HasForeignKey("ObrasExpuestasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("obras_mvc_ef.Models.Obras", b =>
                {
                    b.HasOne("obras_mvc_ef.Models.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId");

                    b.Navigation("Artista");
                });
#pragma warning restore 612, 618
        }
    }
}
